sprint-2/step-1 использование контекста и редьюсера
wozli/react-burger pull request #4
Opened 2022-10-11 13:47 UTC by wozli

2022-10-11 15:43 UTC, randomroot requested changes
**Доброго времени суток!**

Вы **правильно** реализовали работу с контекстом, **круто**, что использовали `useReducer` - это сделало код лаконичнее и удобно организовало работу с состоянием, добавили **классный** лоадер на моменты работы с API - так держать 👍 

Для успешной сдачи работы, вам следует **исправить** следующие моменты:

1) Подсчёт стоимости заказа осуществляется некорректно;
2) При формировании массива идентификаторов следует учитывать порядок элементов, наличие булок и их положение в рамках него;
3) Булка является неудаляемым элементом, согласно дизайну, поэтому следует разрешить повторный выбор любой другой булки и заблокировать его в конструкторе;

Также в рамках ревью были предложены **улучшения** по организации и реализации функциональностей вашего кода, которые предлагаются вам на рассмотрение.

**Желаю вам хорошего настроения и успешного рефакторинга!** 🐈

2022-10-11 15:43 UTC, randomroot commented on src/components/burger-constructor/BurgerConstructor.jsx
> +              <p className={`${BurgerConstructorStyles.info} text text_type_main-medium`}>Добавьте ингредиенты с
🟡 **Можно улучшить:**

Следует исправить слово "слева" в тексте, т.к. сейчас оно отображается раздельно

![image](https://user-images.githubusercontent.com/15111821/195121380-c8952a1e-991f-4983-a68b-36c1cf73ced2.png)

2022-10-11 15:43 UTC, randomroot commented on src/components/burger-constructor/BurgerConstructor.jsx
> +  const notEmptyIngredients = useMemo(() => stateIngredients.ingredients && stateIngredients.ingredients.length, [stateIngredients.ingredients]);
🟡 **Можно улучшить:**

В данном случае использование хука `useMemo` представляется излишним, т.к. проверка массива на пустоту и длину довольно простые операции, по времени занимающие примерно то же время что и сверка схожести массива в рамках массива зависимостей, но добавляющее дополнительные издержки связанные с внутренним устройством хука

2022-10-11 15:43 UTC, randomroot commented on src/components/burger-constructor/BurgerConstructor.jsx
> +                  <ConstructorElement text={`${bun.name} (верх)`}
🔴 **Нужно исправить:**

Согласно дизайну, булка в конструкторе ингредиентов является неудаляемым элементом и может заменяться на другую булку по нажатию (перетаскиванию в будущем). Поэтому следует заблокировать удаление данного компонента и разрешить повторный выбор булки.

![image](https://user-images.githubusercontent.com/15111821/195122815-9e73a1e9-3d9a-486e-b94b-302f23d5883a.png)

2022-10-11 15:43 UTC, randomroot commented on src/services/constructorContenxt.js
> +import React from "react";
🟡 **Можно улучшить:**

В названии файла содержится орфографическая ошибка

2022-10-11 15:43 UTC, randomroot commented on src/pages/constructor/Constructor.jsx
> +    if (idx === - 1) {
🔴 **Нужно исправить:**

Согласно постановки задачи, ограничения на повторное добавление ингредиентов отсутствуют, поэтому следует удалить данную проверку и разрешить пользователю действие.

2022-10-11 15:43 UTC, randomroot commented on src/pages/constructor/Constructor.jsx
> +    if (isBunAlreadyAdd) {
🔴 **Нужно исправить:**

Согласно дизайну, булка является неудаляемым элементом, поэтому следует разрешить повторный выбор булки и заменять ей существующее значение

2022-10-11 15:43 UTC, randomroot commented on src/components/common/loader/loader.jsx
> +function Loader() {
🟢 **Отлично:**

Подход по применению лоадера и его реализация - огонь, так держать 👍

2022-10-11 15:43 UTC, randomroot commented on src/components/utils/api.js
> +export const POST_ORDER = 'https://norma.nomoreparties.space/api/orders';
🟡 **Можно улучшить:**

Общее значение в ссылке на API (`https://norma.nomoreparties.space/api/`) имеет смысл вынести в отдельную константу, т.к. оно не изменяется со временем, вне зависимости от вызываемого метода

2022-10-11 15:43 UTC, randomroot commented on src/components/utils/constants.js
> +}
🟡 **Можно улучшить:**

Хорошо, что решили объединить экшены в рамках одной константы, это удобно. Тем не менее, рекомендую их значения именовать более сложным образом, чтобы было легче отлаживать, когда количество похожих действий будет увеличиваться.

2022-10-11 15:43 UTC, randomroot commented on src/pages/constructor/Constructor.jsx
> +  const {isToggle: isToggleLoader, close: closeLoader, open: openLoader} = useToggle(false);
🟡 **Можно улучшить:**

Использование функций `close` и `open` в рамках хука `useToggle` нецелесообразно, т.к. это немного нарушает логику "выключателя" - действия с таким хуком следует строить так, чтобы было достаточно вызывать функцию `toggle()`, иначе он не будет ничем отличаться от простого `useState`.

В рамках вашего кода логика "выключателя" соблюдается без отдельных функций, поэтому рекомендую откатить изменения до изначального варианта реализации хука.

Если у вас присутствуют сомнения на этот счёт - буду рад услышать ваш комментарий под этим постом, обсудим и примем верное решение 🐈

2022-10-11 15:43 UTC, randomroot commented on src/pages/constructor/Constructor.jsx
> +        totalPrice: state.totalPrice += (action.payload.type === TYPE_INGREDIENTS.BUN ? action.payload.price * 2 : action.payload.price)
🔴 **Нужно исправить:**

Следует заменить операцию присвоения значения на простое суммирование с новым значением, т.к. сейчас происходит ошибочное вычисление двойной цены любого из ингредиентов (а у булки даже четвертной)

![image](https://user-images.githubusercontent.com/15111821/195130665-e665acba-7d65-4c3b-9206-b2da1e858073.png)

2022-10-11 15:43 UTC, randomroot commented on src/services/constructorContenxt.js
> +export const ProductContext = React.createContext(null);
🟡 **Можно улучшить:**

Файл имеет наименование `constructorContext`, однако в нём содержатся 2 контекста - поэтому лучше разделить их по отдельным файлам, чтобы улучшить структура проекта и обеспечить легкий поиск нужного контекста по ней :)

2022-10-11 15:43 UTC, randomroot commented on src/pages/constructor/Constructor.jsx
> +    if (stateIngredients.ingredients && stateIngredients.ingredients.length) {
🔴 **Нужно исправить:**

1) Бургеру сложно будет существовать без булки - поэтому следует добавить проверку на её наличие в списке ингредиентов или вынести в отдельную переменную состояния для более удобного управления ею :)
2) В заказе присутствует две булки - стоимость заказа у вас это уже учитывает, но на сервер отправляется только один её идентификатор;
2) Массив ингредиентов в текущей реализации не учитывает порядок добавления булки и ингредиентов внутри - может получится некорректная комбинация, например `начинка, начинка, булка, соус`. Следует привести её к виду `булка, (ингредиенты), ...булка` - которая отображает правильный порядок :)

2022-10-11 15:52 UTC, wozli commented on src/pages/constructor/Constructor.jsx
> +  const {isToggle: isToggleLoader, close: closeLoader, open: openLoader} = useToggle(false);
потому что toggle не корректно отрабатывает в then, он почему то видит что еще не открыта модалка, да и функции lose и open показывал куратор на вебинаре

2022-10-11 15:53 UTC, wozli commented on src/pages/constructor/Constructor.jsx
> +        totalPrice: state.totalPrice += (action.payload.type === TYPE_INGREDIENTS.BUN ? action.payload.price * 2 : action.payload.price)
это из за StrictMode так, в билде все верно считает

2022-10-11 15:57 UTC, wozli commented on src/components/burger-constructor/BurgerConstructor.jsx
> +                  <ConstructorElement text={`${bun.name} (верх)`}
"Булка является неудаляемым элементом, согласно дизайну, поэтому следует разрешить повторный выбор любой другой булки и заблокировать его в конструкторе;"  - я не понимаю вашей формулировки, если она не удаляемая, как ты выберешь другую булку если место уже занято, надо наверно сначала убрать? Либо кривой как говорится "юзер экспириэнс" дизайна

2022-10-11 16:07 UTC, randomroot commented on src/pages/constructor/Constructor.jsx
> +  const {isToggle: isToggleLoader, close: closeLoader, open: openLoader} = useToggle(false);
Некорректное отрабатывания `toggle` в рамках `then` возможно из-за возникновения замыкания переменной состояния внутри хука. Чтобы это исправить, попробуйте осуществлять смену состояния через `setState(previousState => !previousState)

К сожалению, информации по вебинару у меня отсутствует, поэтому могу предположить, что куратор демонстрировал немного другой хук или логику поведения. В рамках простейшей каноничной реализации `useToggle` можно изучить такой пример: https://usehooks.com/useToggle/

2022-10-11 16:21 UTC, randomroot commented on src/pages/constructor/Constructor.jsx
> +        totalPrice: state.totalPrice += (action.payload.type === TYPE_INGREDIENTS.BUN ? action.payload.price * 2 : action.payload.price)
Вы верно обратили внимание на то, что без `StrictMode` текущая реализация подсчитывает результат верно.

**Однако**, стоит выделить два важных момента, связанных с текущей реализацией:
1) Использование операции присвоения здесь нецелесообразно, т.к. происходит установка переменной стейта значения напрямую, а потом оно же перезаписывается заново объектом, который вы возвращаете из редьюсера.

2) Режим `StrictMode` создан именно для отслеживания ситуаций в которых происходят "побочные эффекты" при выполнении. В данном случае происходит нарушение соглашения о том, что функция редьюсера является "чистой функцией" (см. https://habr.com/ru/post/437512/), т.к. она изменяет входной параметр `state`, что и отображается в двойной наценке стоимости бургера в рамках вышеупомянутого режима (см. https://beta.reactjs.org/apis/react/useReducer#writing-the-reducer-function)

2022-10-11 16:39 UTC, randomroot commented on src/components/burger-constructor/BurgerConstructor.jsx
> +                  <ConstructorElement text={`${bun.name} (верх)`}
Для решения данного вопроса, предлагаю провести **сравнение** предложенного в дизайне UX **(1)** и реализованного вами на данный момент **(2)**:

**(1)**  Пользователь добавляет булку, понимает что ошибся -> Выбирает другую и она заменяет текущую.
**(2)** Пользователь добавляет булку, понимает что ошибся -> Удаляет текущую булку -> Добавляет новую из списка;

С учётом, что заказ не следует создавать без булок, вы можете увидеть, что вариант, предложенный дизайнерами, предлагает на **одно действие меньше** для пользователя, что **экономит ему время**.

С точки зрения **реализации первого подхода** можно пойти двумя путями:
1) Хранить значение булки прямо в списке ингредиентов и в рамках замены сначала убрать его, а потом добавить новое (т.е. выполнить действия пользователя текущей реализации за кулисами);
2) Переместить булку в отдельную переменную в стейте контекста и работать с ней, просто заменяя значение на новое.

2022-10-11 16:45 UTC, wozli commented on src/components/burger-constructor/BurgerConstructor.jsx
> +                  <ConstructorElement text={`${bun.name} (верх)`}
теперь понятней стало, просто нигде не сказано, что при выборе булки она заменится на новую, тогда другой вопрос как пользователь выборочно заменит нижнюю или верхнюю булку если они выбраны? кликаю слева на булку и какая тогда заменится?

2022-10-11 16:53 UTC, randomroot commented on src/components/burger-constructor/BurgerConstructor.jsx
> +                  <ConstructorElement text={`${bun.name} (верх)`}
**Выборочное** изменение (комбинирование) булок в рамках конструктора **недоступны**, согласно ТЗ:

![image](https://user-images.githubusercontent.com/15111821/195152444-6da6b5fd-f1b4-4f37-8cbe-a33329fa2dc9.png)

Поэтому, по нажатию на булку производится замена **как верхней, так и нижней** булки. Именно поэтому, было внесено предложение по выделению значения текущей выбранной булки в отдельную переменную 🐱 

_P.S. Да, к сожалению, формулировки задания могут быть неточными или не совсем очевидными, рекомендую подсветить этот момент в соответствующей форме обратной связи - составители заданий изучат и внесут необходимые коррективы :)_

2022-10-11 16:58 UTC, wozli commented on src/components/burger-constructor/BurgerConstructor.jsx
> +                  <ConstructorElement text={`${bun.name} (верх)`}
то есть я когда кликаю булку слева она должна встать и вниз и вверх так? я не могу выбрать разные булки для верха и низа?

2022-10-11 17:01 UTC, randomroot commented on src/components/burger-constructor/BurgerConstructor.jsx
> +                  <ConstructorElement text={`${bun.name} (верх)`}
Всё верно, она должна встать и вниз и вверх. Выбор разных не разрешается условиями задачи.

2022-10-11 17:02 UTC, wozli commented on src/components/burger-constructor/BurgerConstructor.jsx
> +                  <ConstructorElement text={`${bun.name} (верх)`}
спасибо)

2022-10-12 07:50 UTC, randomroot approved these changes
🟢 **Работа принята!**

Все необходимые исправления были **оперативно** внесены, **учтены** предложенные улучшения. **Отлично**, что стараетесь разобраться в отмеченных проблемах и выносите на обсуждение, совместными усилиями всегда получается результат еще лучше 👍 

**Отличного вам дня и успехов!** 🐈

2022-10-12 07:50 UTC, randomroot commented on src/hooks/useToggle.js
> +    setIsToggle(previousState => !previousState);
🟡 **Можно улучшить:**

Функции `open` и `close` теперь совпадают полностью, поэтому можно действие по смене стейте перенести прямо в `toggle` и удалить две функции :)

2022-10-12 07:50 UTC, randomroot commented on src/pages/constructor/Constructor.jsx
> +    if (selectBun && selectBun._id && selectIngredients && selectIngredients.length) {
🟡 **Можно улучшить:**

Заказ без булок создавать не следует, это верно, однако ингредиенты не являются обязательной частью бутерброда - дадим же шанс любителям покушать всухомятку! :)

2022-10-12 10:03 UTC, merged