Переход на ts
wozli/react-burger pull request #7
Opened 2022-11-24 15:55 UTC by wozli

2022-11-24 19:40 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали **прекрасную** работу по типизации вашего проекта, отлично, что уже **заранее типизировали** и ваш стор вместе с хуками `useStore` и `useDispatch`, **практически отсутствует** `any` типизация, **так держать** 👍 

**Тем не менее**, для успешной сдачи работы вам следует внимательно ознакомиться с комментариями, оставленными в рамках ревью и произвести необходимые корректировки, обратив внимание на следующие моменты:

- Для всех запросов в рамках проекта, следует типизировать ответ получаемый с сервера, т.к. в текущей реализации у вас `data` имеет тип `any`. что не позволяет однозначно ответить на вопрос, какая структура данных в ней содержится;
- Названия параметров функции, которые написаны через нижнее подчеркивание в слайсах следует привести к формату `camelCase`;
- Использование типа `object` практически эквиваленту типу `any`;

Также, в рамках работы были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга и хорошего настроения!** 🐈

2022-11-24 19:40 UTC, randomroot commented on src/services/slices/auth.ts
> +    async (register_info: { password: string, email: string, name: string }) => {
🔴 **Нужно исправить:**

**Здесь и далее по коду:** названия параметров функции следует привести к формату `camelCase`

2022-11-24 19:40 UTC, randomroot commented on src/services/slices/auth.ts
> +    async (new_user_info: object) => {
🔴 **Нужно исправить:**

Следует уточнить типизацию параметра функции, использование `object` является не совсем удачной практикой, т.к. позволяет передать абсолютно любой объект в функцию, тем самым отключив возможности проверки типов в коде

2022-11-24 19:40 UTC, randomroot commented on src/services/slices/auth.ts
> +            return response.data;
🔴 **Нужно исправить:**

**Для всех запросов в рамках проекта:**
Следует типизировать ответ получаемый с сервера, т.к. в текущей реализации у вас `data` имеет тип `any`. что не позволяет однозначно ответить на вопрос, какая структура данных в ней содержится

2022-11-24 19:40 UTC, randomroot commented on src/services/slices/auth.ts
> +    //   [getUser.pending]: (state) => {
🟡 **Можно улучшить:**

Неиспользуемый код имеет смысл удалять из файлов, чтобы поддерживать чистоту кода. В случае необходимости его восстановления можно воспользоваться средствами Git-a.

2022-11-24 19:40 UTC, randomroot commented on src/services/slices/order.ts
> +    // extraReducers: {
🟡 **Можно улучшить:**

Неиспользуемый код имеет смысл удалять из файлов, чтобы поддерживать чистоту кода. В случае необходимости его восстановления можно воспользоваться средствами Git-a.

2022-11-24 19:40 UTC, randomroot commented on src/components/common/modal/Modal.tsx
> +function Modal({children, onClose}: TModalProps) {
🟡 **Можно улучшить:**

Если воспользоваться интерфейсом `FC`, то можно не типизировать самостоятельно `children` (до 18-ого реакта, там эту фичу убрали)

2022-11-25 06:15 UTC, wozli commented on src/services/slices/auth.ts
> +            return response.data;
А можно пример типизации, там же еще headers приходит в респонсе и еще коешчто как это типизировать

2022-11-25 06:23 UTC, wozli commented on src/components/common/modal/Modal.tsx
> +function Modal({children, onClose}: TModalProps) {
у меня 18)_))

2022-11-25 06:54 UTC, wozli commented on src/services/slices/auth.ts
> +            return response.data;
![image](https://user-images.githubusercontent.com/45283181/203918662-61dc3d1d-17aa-410d-9efa-6bdf46917793.png)
вот я без обертки сделал и затипизировал, так верно?

2022-11-25 07:00 UTC, wozli commented on src/services/slices/auth.ts
> +            return response.data;
или с интерфейсом лучше 
![image](https://user-images.githubusercontent.com/45283181/203920659-48e98354-db53-4f55-8e72-1564570a9f2e.png)

2022-11-25 07:17 UTC, randomroot commented on src/services/slices/auth.ts
> +            return response.data;
Да, для аксиоса такой подход правильный, можно либо напрямую (как у вас), либо создать отдельный интерфейс/тип, чтобы было нагляднее)

Отвечая на вопрос выше: такой типизации вполне достаточно, хедеры и другие моменты автоматически получат свои типы, важно только передать тип для данных.

2022-11-25 07:37 UTC, wozli commented on src/services/slices/auth.ts
> +            return response.data;
@randomroot у меня начинает в then ругаться на payload 
![image](https://user-images.githubusercontent.com/45283181/203926414-67d87e05-16a2-46ad-852b-9632179ae46c.png)
![image](https://user-images.githubusercontent.com/45283181/203926459-db12aa8f-512c-4444-876f-2592c7451dbe.png)

2022-11-25 08:38 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, так держать👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-12-09 13:09 UTC, merged