tests and deploy
wozli/react-burger pull request #9
Opened 2022-12-21 09:28 UTC by wozli

2022-12-21 09:30 UTC, wozli commented
Для простых редьюсеров с обычным присваиванием где нет логики, тесты не писал

2022-12-21 11:46 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали хорошую работу по добавлению тестов в ваш проект, обеспечили проход по процессу создания заказа. Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Следует обеспечить **максимально возможное покрытие** тестами всех строк кода редьюсеров, согласно условиям задания (покрытие см. https://disk.yandex.ru/i/fXsRsaDVBz2rIQ).  Проверить покрытие кода вы можете с помощью команды `npm test -- --coverage --watchAll=false`
- Следует скорректировать **интеграционный** тест в Cypress разбив его на отдельные независимые части (создание заказа / открытие модального окна с ингредиентов) и обеспечить дополнительные проверки на наличие/отсутствие элементов на экране после произведенных действий.
- В `README.md` следует указать ссылку на ваш проект, размещенный на _Github Pages_

В качестве возможного улучшения тестирования предлагается вместо прямого обращения к API использовать `fixtures` (см. https://docs.cypress.io/api/commands/fixture), чтобы сделать процесс **независимым от бэкенда и наличия сети**.

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2022-12-21 11:46 UTC, randomroot commented on cypress/e2e/is-available.cy.ts
> +    cy.intercept('POST', 'https://norma.nomoreparties.space/api/orders').as('orders')
🟡 **Можно улучшить:**

Лучше тестировать приложение не на боевом сервере,
а либо поднять тестовый сервер отдельно (что в нашей ситуации не представляется
возможным) или мокать запросы. При этом `cypress` будет перехватывать
запросы и возращать результаты с данными из файлов из папки `fixtures`
Т.к. иначе мы тестируем не только фронтенд, а и бэкенд. Так же изменения данных
на бэке могут сломать тесты (например если изменятся ингредиенты) или мы можем 
там сломать что нибудь ненужными запрсоами

Пример мока запросов:
```js
beforeEach(function () {
	cy.intercept("GET", "api/ingredients", { fixture: "ingredients.json" });
})
```
где `ingredients.json` - файл в папке fixtures содержащий данные ингредиентов

Подробнее о fixtures можно прочитать в документации
(см. https://docs.cypress.io/api/commands/fixture)

2022-12-21 11:46 UTC, randomroot commented on cypress/e2e/is-available.cy.ts
> +  it('passes', () => {
🔴 **Нужно исправить:**

Не следует все тесты проводить в рамках одного тест-кейса. Каждый тестируемый функционал следует разместить в отдельном тесте с описанием, что в нём происходит (вариант `passes` является некорректным, т.к. не ясно, что именно тестируется здесь и какой результат ожидается).

2022-12-21 11:46 UTC, randomroot commented on cypress/e2e/is-available.cy.ts
> +    cy.get('[class^=Modal_modal__close__]').first().as('modalClose1');
🔴 **Нужно исправить:**

1) Перед закрытием окна следует удостовериться, что на экране отображается информация о выбранном ингредиенте;
2) После закрытия окна следует удостовериться, что окно действительно закрылось и больше не присутствует на экране

2022-12-21 11:46 UTC, randomroot commented on cypress/e2e/is-available.cy.ts
> +    cy.get('@container').get('[class^=button]').click();
🔴 **Нужно исправить:**

После перетаскивания ингредиента в конструктор следует удостовериться, что действие произошло успешно и он появился в списке конструктора с правильным наполнением

2022-12-21 11:46 UTC, randomroot commented on cypress/e2e/is-available.cy.ts
> +    cy.get('@modalClose1').click();
🔴 **Нужно исправить:**

1) Перед закрытием модального окна следует удостовериться, что поле номера заказа содержит значение
2) После закрытия окна следует удостовериться, что окно действительно закрылось и больше не присутствует на экране

2022-12-23 09:07 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-12-23 09:52 UTC, merged